# Generated by Django 6.1 on 2026-08-14 11:38

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('supercasas', 'Supercasas')], default='supercasas', max_length=30)),
                ('source_listing_id', models.CharField(max_length=50)),
                ('source_url', models.URLField(max_length=500)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartamento')], default='apartment', max_length=30)),
                ('operation_type', models.CharField(choices=[('sale', 'Venta')], default='sale', max_length=30)),
                ('sector', models.CharField(max_length=100)),
                ('city', models.CharField(default='Santo Domingo', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('DOP', 'Peso Dominicano')], default='USD', max_length=3)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=4, null=True)),
                ('parking_spaces', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['sector', 'property_type', 'operation_type'], name='listings_li_sector_d52b02_idx'), models.Index(fields=['is_active', 'last_seen_at'], name='listings_li_is_acti_c249a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_listing_id'), name='unique_source_listing_id')],
            },
        ),
    ]
