# Generated by Django 6.1 on 2026-08-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='source',
            field=models.CharField(choices=[('demo', 'Datos de demostración'), ('manual', 'Carga manual o autorizada'), ('supercasas', 'Supercasas')], default='supercasas', max_length=30),
        ),
    ]
