# Generated by Django 6.1 on 2026-08-21 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('DOP', 'Peso Dominicano')], max_length=3)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='listings.listing')),
            ],
        ),
    ]
