# Generated by Django 6.1 on 2026-08-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingpricesnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingpricesnapshot',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AddIndex(
            model_name='listingpricesnapshot',
            index=models.Index(fields=['listing', 'recorded_at'], name='listings_li_listing_e7c3e1_idx'),
        ),
    ]
